### ISSUE TITLE
优化异常处理

### ISSUE THREAD

**Issue by gtn1024** [aruis/MuYun#18]
1. 应使用自定义异常代替 `assert`

https://github.com/aruis/MuYun/blob/master/my-core/src/main/java/net/ximatai/muyun/core/ability/curd/IUpdateAbility.java#L20

2. 细化数据库异常，针对不同的数据库错误类型创建不同的异常
3. 全局细粒度拦截不同的异常
4. 针对客户的发来的请求，出现异常，抛出 4xx 错误更好

**Comment by aruis** [comment]
👌
