### ISSUE TITLE
本项目采用什么开源协议比较好，大家有想法可以提出来。

### ISSUE THREAD

**Issue by aruis** [aruis/MuYun#5]

**Comment by aruis** [comment]
@weizhiwen @gtn1024  😃

**Comment by Codeprh** [comment]
grpc

**Comment by weizhiwen** [comment]
我觉得应该使用Apache license 2协议，限制少可修改，但是作者保有专利

**Comment by aruis** [comment]
我也刚调研了下，觉得 Apache License 2.0 相对来说还是比较友好，切能保护专利的。 你的意见呢？  @gtn1024

**Comment by gtn1024** [comment]
我个人更加偏向 AGPL 等更加严格的开源协议，个人使用/公司内部使用免费，对外提供服务收费

**Comment by aruis** [comment]
那就这样，先采用 Apache License 2.0 ，未来功能丰富到一定程度再考虑用更严格的协议。

**Comment by aruis** [comment]
#6
